chrome|https://github.com/kralicekgamer/WPM/raw/refs/heads/main/chrome/{channel}/setup|exe|latest|Kralyks WPM
discord|https://github.com/kralicekgamer/WPM/raw/refs/heads/main/discord/{channel}/setup|exe|latest|Kralyks WPM
vscode|https://github.com/kralicekgamer/WPM/raw/refs/heads/main/vsc/{channel}/setup|exe|latest|Kralyks WPM
tor-browser|https://github.com/kralicekgamer/WPM/raw/refs/heads/main/tor-browser/{channel}/setup|exe|latest|Kralyks WPM
zen-browser|https://github.com/kralicekgamer/WPM/raw/refs/heads/main/zen-browser/{channel}/setup|exe|latest|Kralyks WPM
krita|https://github.com/kralicekgamer/WPM/raw/refs/heads/main/krita/{channel}/setup|exe|latest|Kralyks WPM
python|https://github.com/kralicekgamer/WPM/raw/refs/heads/main/python/{channel}/setup|exe|latest|Kralyks WPM
spotify|https://github.com/kralicekgamer/WPM/raw/refs/heads/main/spotify/{channel}/setup|exe|latest|Kralyks WPM
firefox|https://github.com/kralicekgamer/WPM/raw/refs/heads/main/firefox/{channel}/setup|exe|latest|Kralyks WPM
libreoffice|https://github.com/kralicekgamer/WPM/raw/refs/heads/main/libre-office/{channel}/setup|msi|latest|Kralyks WPM
telegram|https://github.com/kralicekgamer/WPM/raw/refs/heads/main/telegram/{channel}/setup|exe|latest|Kralyks WPM
vlc|https://github.com/kralicekgamer/WPM/raw/refs/heads/main/vlc/{channel}/setup|exe|latest|Kralyks WPM
7zip|https://github.com/kralicekgamer/WPM/raw/refs/heads/main/7zip/{channel}/setup|exe|latest|Kralyks WPM
adobe-acrobat-reader|https://github.com/kralicekgamer/WPM/raw/refs/heads/main/adobe-acrobat-reader/{channel}/setup|exe|latest|Kralyks WPM
